-- PostgreSQL baseline for the CAA recruitment modular monolith.
-- Legacy source columns are retained to support a staged MySQL data migration.

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    account_type varchar(20) NOT NULL DEFAULT 'external'
        CHECK (account_type IN ('external', 'internal', 'admin')),
    admin_role varchar(30)
        CHECK (admin_role IS NULL OR admin_role IN
               ('super', 'hr', 'recruiter', 'auditor', 'hr_officer', 'it_admin', 'dhra', 'hod')),
    employee_number varchar(50),
    effective_type varchar(20) NOT NULL DEFAULT 'external'
        CHECK (effective_type IN ('external', 'internal', 'admin')),
    email_verified boolean NOT NULL DEFAULT true,
    verify_token varchar(64),
    is_active boolean NOT NULL DEFAULT true,
    token_version integer NOT NULL DEFAULT 0 CHECK (token_version >= 0),
    reset_token_hash varchar(64),
    reset_token_expires timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_admin_role CHECK (
        (account_type = 'admin' AND admin_role IS NOT NULL)
        OR (account_type <> 'admin' AND admin_role IS NULL)
    )
);
CREATE UNIQUE INDEX uq_users_email_ci ON users (lower(email));
CREATE INDEX idx_users_employee_number ON users (employee_number) WHERE employee_number IS NOT NULL;
CREATE INDEX idx_users_active_type ON users (is_active, account_type);

CREATE TABLE staff (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint UNIQUE REFERENCES users(id) ON DELETE SET NULL,
    employee_number varchar(50) NOT NULL UNIQUE,
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    dept varchar(100),
    position varchar(255),
    email varchar(255),
    joined_date date,
    status varchar(50) NOT NULL DEFAULT 'Active',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX uq_staff_email_ci ON staff (lower(email)) WHERE email IS NOT NULL;
CREATE INDEX idx_staff_status ON staff (status);

CREATE TABLE departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    code varchar(20) NOT NULL UNIQUE,
    head_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_departments_head_user ON departments (head_user_id);

CREATE TABLE jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    abbr varchar(10) NOT NULL,
    title varchar(255) NOT NULL,
    dept varchar(100) NOT NULL,
    dept_key varchar(50) NOT NULL,
    location varchar(100) NOT NULL DEFAULT 'Entebbe, Uganda',
    salary varchar(100) NOT NULL,
    salary_band varchar(3) NOT NULL CHECK (salary_band IN ('UG1','UG2','UG3','UG4','UG5','UG6','UG7')),
    type varchar(30) NOT NULL DEFAULT 'Full-time'
        CHECK (type IN ('Full-time','Contract','Fixed Term Contract')),
    closes varchar(50) NOT NULL,
    closes_at date NOT NULL,
    visibility varchar(20) NOT NULL DEFAULT 'external'
        CHECK (visibility IN ('external','internal','closed')),
    min_age integer NOT NULL DEFAULT 21 CHECK (min_age >= 0),
    required_experience integer NOT NULL DEFAULT 0 CHECK (required_experience >= 0),
    required_qualification varchar(50) NOT NULL,
    description text,
    featured boolean NOT NULL DEFAULT false,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status varchar(30) NOT NULL DEFAULT 'published'
        CHECK (status IN ('draft','pending_review','pending_approval','published','declined')),
    department_id bigint REFERENCES departments(id) ON DELETE SET NULL,
    reviewed_by bigint REFERENCES users(id) ON DELETE SET NULL,
    approved_by bigint REFERENCES users(id) ON DELETE SET NULL,
    decline_reason text,
    job_ref varchar(100),
    reports_to varchar(255),
    vacancies integer NOT NULL DEFAULT 1 CHECK (vacancies > 0),
    about_role text,
    accountabilities jsonb,
    special_skills jsonb,
    CONSTRAINT ck_jobs_decline_reason CHECK (status <> 'declined' OR decline_reason IS NOT NULL)
);
CREATE INDEX idx_jobs_visibility_status_close ON jobs (visibility, status, closes_at);
CREATE INDEX idx_jobs_department ON jobs (department_id);
CREATE INDEX idx_jobs_created_by ON jobs (created_by);
CREATE UNIQUE INDEX uq_jobs_job_ref ON jobs (job_ref) WHERE job_ref IS NOT NULL;

CREATE TABLE applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    candidate_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    candidate_email varchar(255) NOT NULL,
    candidate_name varchar(255) NOT NULL,
    abbr varchar(10) NOT NULL,
    title varchar(255) NOT NULL,
    dept varchar(100) NOT NULL,
    date varchar(50) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'Pending'
        CHECK (status IN ('Pending','Under Review','Shortlisted','Shortlisted II','Interview',
                          'Assessment Scheduled','Assessment Complete','Offered','Declined','Withdrawn')),
    completion integer NOT NULL DEFAULT 0 CHECK (completion BETWEEN 0 AND 100),
    cgpa numeric(3,2) CHECK (cgpa IS NULL OR cgpa BETWEEN 0 AND 5),
    university varchar(255),
    screening_answers jsonb,
    applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deployment_station varchar(255),
    deployment_date date,
    CONSTRAINT uq_application UNIQUE (job_id, candidate_email),
    CONSTRAINT ck_application_deployment CHECK (
        (deployment_station IS NULL AND deployment_date IS NULL)
        OR (deployment_station IS NOT NULL AND deployment_date IS NOT NULL)
    )
);
CREATE INDEX idx_applications_email_ci ON applications (lower(candidate_email));
CREATE INDEX idx_applications_candidate_user ON applications (candidate_user_id);
CREATE INDEX idx_applications_job_status ON applications (job_id, status);
CREATE INDEX idx_applications_applied_at ON applications (applied_at DESC);

CREATE TABLE cv_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    user_email varchar(255) NOT NULL UNIQUE,
    personal_data jsonb NOT NULL DEFAULT '{}'::jsonb,
    highest_level varchar(50),
    qualifications jsonb NOT NULL DEFAULT '[]'::jsonb,
    skills jsonb NOT NULL DEFAULT '[]'::jsonb,
    experience jsonb NOT NULL DEFAULT '[]'::jsonb,
    referees jsonb NOT NULL DEFAULT '[]'::jsonb,
    next_of_kin jsonb NOT NULL DEFAULT '{}'::jsonb,
    photo_url text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_cv_profiles_user_email_ci ON cv_profiles (lower(user_email));

CREATE TABLE criteria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL UNIQUE REFERENCES jobs(id) ON DELETE CASCADE,
    min_cgpa numeric(3,2) CHECK (min_cgpa IS NULL OR min_cgpa BETWEEN 0 AND 5),
    required_keywords jsonb NOT NULL DEFAULT '[]'::jsonb,
    notes text,
    screening_questions jsonb,
    min_experience_years integer CHECK (min_experience_years IS NULL OR min_experience_years >= 0),
    required_qual_level varchar(50),
    disqualifying_universities jsonb,
    assessment_types jsonb,
    requirements jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_criteria_keywords_array CHECK (jsonb_typeof(required_keywords) = 'array')
);

CREATE TABLE settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_name varchar(255) NOT NULL DEFAULT 'Uganda Civil Aviation Authority',
    email_sender_name varchar(255) NOT NULL DEFAULT 'CAA HR Team',
    min_age_threshold integer NOT NULL DEFAULT 21 CHECK (min_age_threshold >= 0),
    allow_external_internal_jobs boolean NOT NULL DEFAULT false,
    session_timeout_minutes integer NOT NULL DEFAULT 30 CHECK (session_timeout_minutes > 0),
    closing_soon_days integer NOT NULL DEFAULT 7 CHECK (closing_soon_days >= 0),
    max_applications_per_candidate integer NOT NULL DEFAULT 5 CHECK (max_applications_per_candidate > 0),
    notif_template_shortlist text,
    notif_template_decline text,
    notif_template_interview text,
    notif_template_offer text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permission_overrides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id bigint UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    email varchar(255),
    role varchar(50),
    can_view_applications boolean NOT NULL DEFAULT true,
    can_shortlist boolean NOT NULL DEFAULT false,
    can_screen_interns boolean NOT NULL DEFAULT false,
    can_send_notifications boolean NOT NULL DEFAULT false,
    can_manage_jobs boolean NOT NULL DEFAULT false,
    can_manage_criteria boolean NOT NULL DEFAULT false,
    can_view_staff boolean NOT NULL DEFAULT false,
    can_export boolean NOT NULL DEFAULT false,
    can_view_audit boolean NOT NULL DEFAULT false,
    can_manage_settings boolean NOT NULL DEFAULT false,
    can_grant_permissions boolean NOT NULL DEFAULT false,
    can_review_job boolean NOT NULL DEFAULT false,
    can_approve_job boolean NOT NULL DEFAULT false,
    can_manage_departments boolean NOT NULL DEFAULT false,
    can_manage_admins boolean NOT NULL DEFAULT false,
    can_assign_rights boolean NOT NULL DEFAULT false,
    can_schedule_assessment boolean NOT NULL DEFAULT false,
    can_record_assessment boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_permission_override_identity CHECK (admin_id IS NOT NULL OR email IS NOT NULL)
);
CREATE UNIQUE INDEX uq_permission_overrides_email_ci
    ON permission_overrides (lower(email)) WHERE email IS NOT NULL;

CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id bigint REFERENCES users(id) ON DELETE CASCADE,
    recipient_email varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    type varchar(20) NOT NULL DEFAULT 'info'
        CHECK (type IN ('shortlisted','declined','interview','offered','info')),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notifications_recipient_read
    ON notifications (recipient_user_id, is_read, created_at DESC);
CREATE INDEX idx_notifications_email_ci ON notifications (lower(recipient_email), created_at DESC);

CREATE TABLE sent_emails (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    to_email varchar(255) NOT NULL,
    candidate_name varchar(255) NOT NULL,
    subject varchar(500) NOT NULL,
    body text NOT NULL,
    trigger_event varchar(100) NOT NULL,
    job_title varchar(255) NOT NULL,
    sent_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_sent_emails_to_email_ci ON sent_emails (lower(to_email), sent_at DESC);
CREATE INDEX idx_sent_emails_trigger ON sent_emails (trigger_event, sent_at DESC);

CREATE TABLE audit_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor varchar(255) NOT NULL,
    role varchar(100) NOT NULL,
    action varchar(255) NOT NULL,
    target varchar(500),
    actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    correlation_id varchar(128),
    source_ip inet,
    user_agent varchar(500),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX idx_audit_at ON audit_log (at DESC);
CREATE INDEX idx_audit_actor_user ON audit_log (actor_user_id, at DESC);
CREATE INDEX idx_audit_action ON audit_log (action, at DESC);
CREATE INDEX idx_audit_correlation ON audit_log (correlation_id) WHERE correlation_id IS NOT NULL;

CREATE TABLE analytics_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type varchar(20) NOT NULL
        CHECK (event_type IN ('page_view','job_view','apply_click','save_job','search')),
    job_id bigint REFERENCES jobs(id) ON DELETE SET NULL,
    actor_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    job_title varchar(255),
    query varchar(500),
    session_id varchar(255),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_analytics_type_created ON analytics_events (event_type, created_at DESC);
CREATE INDEX idx_analytics_job_created ON analytics_events (job_id, created_at DESC);
CREATE INDEX idx_analytics_session ON analytics_events (session_id) WHERE session_id IS NOT NULL;

CREATE TABLE chatbot_queries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    query varchar(500) NOT NULL,
    matched_question varchar(255),
    outcome varchar(20) NOT NULL CHECK (outcome IN ('answered','suggested','fallback')),
    persona varchar(20) NOT NULL DEFAULT 'guest',
    asked_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_chatbot_outcome_date ON chatbot_queries (outcome, asked_at DESC);

CREATE TABLE assessments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    type varchar(20) NOT NULL CHECK (type IN ('written','psychometric','interview','practical')),
    scheduled_at timestamptz,
    venue varchar(255),
    scheduled_by bigint REFERENCES users(id) ON DELETE SET NULL,
    score numeric(5,2) CHECK (score IS NULL OR score BETWEEN 0 AND 100),
    passed boolean,
    notes text,
    recorded_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_assessment_application_type UNIQUE (application_id, type),
    CONSTRAINT ck_assessment_result CHECK (
        (score IS NULL AND passed IS NULL AND recorded_by IS NULL)
        OR (score IS NOT NULL AND passed IS NOT NULL AND recorded_by IS NOT NULL)
    )
);
CREATE INDEX idx_assessments_scheduled ON assessments (scheduled_at) WHERE scheduled_at IS NOT NULL;

CREATE TABLE job_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL,
    department_id bigint REFERENCES departments(id) ON DELETE SET NULL,
    source_job_id bigint REFERENCES jobs(id) ON DELETE SET NULL,
    content jsonb NOT NULL,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_job_template_content_object CHECK (jsonb_typeof(content) = 'object')
);
CREATE INDEX idx_job_templates_department ON job_templates (department_id);

CREATE TABLE candidate_scores (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
    scorer_user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    score numeric(5,2) NOT NULL CHECK (score BETWEEN 0 AND 100),
    comment text,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_candidate_score_application_scorer UNIQUE (application_id, scorer_user_id)
);
CREATE INDEX idx_candidate_scores_application ON candidate_scores (application_id);
CREATE INDEX idx_candidate_scores_scorer ON candidate_scores (scorer_user_id);

CREATE TABLE refresh_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash varchar(128) NOT NULL UNIQUE,
    token_version integer NOT NULL CHECK (token_version >= 0),
    issued_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at timestamptz NOT NULL,
    last_used_at timestamptz,
    revoked_at timestamptz,
    replaced_by_session_id bigint REFERENCES refresh_sessions(id) ON DELETE SET NULL,
    created_ip inet,
    user_agent varchar(500),
    CONSTRAINT ck_refresh_session_expiry CHECK (expires_at > issued_at),
    CONSTRAINT ck_refresh_session_revocation CHECK (revoked_at IS NULL OR revoked_at >= issued_at)
);
CREATE INDEX idx_refresh_sessions_user_active
    ON refresh_sessions (user_id, expires_at) WHERE revoked_at IS NULL;
CREATE INDEX idx_refresh_sessions_expiry ON refresh_sessions (expires_at);

CREATE TABLE outbox_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id uuid NOT NULL UNIQUE,
    aggregate_type varchar(100) NOT NULL,
    aggregate_id varchar(100) NOT NULL,
    event_type varchar(150) NOT NULL,
    payload jsonb NOT NULL,
    headers jsonb NOT NULL DEFAULT '{}'::jsonb,
    occurred_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    available_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at timestamptz,
    attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    last_error text
);
CREATE INDEX idx_outbox_unpublished
    ON outbox_events (available_at, occurred_at) WHERE published_at IS NULL;

COMMENT ON COLUMN applications.candidate_email IS
    'Legacy/API-compatible source identity retained during user_id backfill.';
COMMENT ON COLUMN cv_profiles.user_email IS
    'Legacy/API-compatible source identity retained during user_id backfill.';
COMMENT ON COLUMN notifications.recipient_email IS
    'Legacy/API-compatible delivery address retained alongside recipient_user_id.';
COMMENT ON TABLE outbox_events IS
    'Transactional outbox; publishing workers are intentionally outside this foundation.';
