CREATE TABLE interview_panel_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
    staff_id bigint NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
    invited_by bigint REFERENCES users(id) ON DELETE SET NULL,
    invited_by_name varchar(255),
    invited_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (job_id, staff_id)
);

CREATE INDEX idx_panel_members_job ON interview_panel_members (job_id);
CREATE INDEX idx_panel_members_staff ON interview_panel_members (staff_id);

COMMENT ON TABLE interview_panel_members IS
    'Staff selected onto a job''s interview panel. Adding a row triggers an automatic invitation email via the outbox.';
